# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               The Objectified Programmer
tagline:             '.NET and web development'
description:         'A husband, a father, a coder, a coffee addict'
url:                 http://theobjectifiedprogrammer.com
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Simon Reynolds
  url:               https://twitter.com/ImSimonReynolds
  email:             simon@theobjectifiedprogrammer.com

# Custom vars
version:             1.0.0
