# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Simon Taite
tagline:             '.NET and web development'
description:         'A husband, a father, a coder, a coffee addict'
url:                 https://simontaite.com
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Simon Taite
  url:               https://twitter.com/ImSimonTaite
  email:             simon@simontaite.com

# Custom vars
version:             1.0.0

theme: jekyll-theme-midnight